# Sean Zaretzky 209164086 tirgul group: 03
# Yaniv Zimmer 318849908 tirgul group: 05

a.out: compileAll
	g++ -o ../../exe/server.out *.o -pthread
	rm -f *.o

compileAll: *.h *.cpp
	g++ -c *.cpp -pthread
